# see https://github.com/ankane/blazer for more info

data_sources:
  main:
    url: <%= ENV['BLAZER_DATABASE_URL'] %>

    # statement timeout, in seconds
    timeout: 15

    # caching settings
    cache:
      mode: all
      expires_in: 60

    smart_variables:
      # zone_id: "SELECT id, name FROM zones ORDER BY name ASC"
      # period: ["day", "week", "month"]
      # status: {0: "Active", 1: "Archived"}

    linked_columns:
      salesforce_id: "https://openstax.lightning.force.com/lightning/r/{value}/view"

    smart_columns:
      user_id: "SELECT id, first_name last_name FROM users WHERE id IN {value}"

# create audits
# audit: true

# run queries async
# async: true

# change the time zone
time_zone: "Central Time (US & Canada)"

# class name of the user model
user_class: User

# method name for the current user
# user_method: current_user

# method name for the display name
# user_name: name

# custom before_action to use for auth
# before_action_method: require_admin

# webhook for Slack
# slack_webhook_url: <%= ENV["BLAZER_SLACK_WEBHOOK_URL"] %>

check_schedules:
  - "1 day"
  - "1 hour"
  - "5 minutes"
